


// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `MainConnectionString`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Server=.;Database=ProjectManager;User Id=sa;password=**zapped**;`
//     Schema:                 ``
//     Include Views:          `False`

//     Factory Name:          `SqlClientFactory`

// -----------------------------------------------------------------------------------------
// Failed to read database schema - A connection was successfully established with the server, but then an error occurred during the login process. (provider: Shared Memory Provider, error: 0 - No process is on the other end of the pipe.)
// -----------------------------------------------------------------------------------------

